# Generated by Django 3.2.16 on 2023-11-14 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KhmQuestionsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Сумма выигрыша')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='KhmQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, verbose_name='Текст вопроса')),
                ('answer_a', models.CharField(db_index=True, max_length=255, verbose_name='Ответ A')),
                ('answer_b', models.CharField(db_index=True, max_length=255, verbose_name='Ответ B')),
                ('answer_c', models.CharField(db_index=True, max_length=255, verbose_name='Ответ C')),
                ('answer_d', models.CharField(db_index=True, max_length=255, verbose_name='Ответ D')),
                ('trueanswer', models.CharField(db_index=True, max_length=255, verbose_name='Вариант правильного ответа')),
                ('time_create', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Публикация')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='khm_questions.khmquestionscategory', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
