# Generated by Django 3.2.16 on 2023-11-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khm_questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khmquestions',
            old_name='answer_a',
            new_name='answer_A',
        ),
        migrations.RenameField(
            model_name='khmquestions',
            old_name='answer_b',
            new_name='answer_B',
        ),
        migrations.RenameField(
            model_name='khmquestions',
            old_name='answer_c',
            new_name='answer_C',
        ),
        migrations.RenameField(
            model_name='khmquestions',
            old_name='answer_d',
            new_name='answer_D',
        ),
    ]
